function zfunc = zfunc(x,y,z,a,b,c,d,e,f,g,h,m,s)
%ZFUNC
%    ZFUNC = ZFUNC(X,Y,Z,A,B,C,D,E,F,G,H,M,S)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    18-Mar-2013 09:12:34

t2 = 1.0./m;
t3 = 1.0./m.^2;
zfunc = s+x.^2.*(a.*t2.*(1.0./2.0)-e.*g.*t3.*(1.0./2.0))+y.^2.*(b.*t2.*(1.0./2.0)-f.*h.*t3.*(1.0./2.0))+x.*y.*(d.*t2-f.*g.*t3)+g.*t2.*x+h.*t2.*y;
